version: '2'
services:
  oracle:
    # sid: xe
    # username: system
    # password: oracle
    image: oracleinanutshell/oracle-xe-11g
    restart: always 
    container_name: oracle
    volumes:
      - ./data:/usr/oracle
    ports:
      - 1521:1521
