sqoop export \
--connect jdbc:oracle:thin:@192.168.31.203:1521:orcl \
--username devp_gwcs \
--password Aa123456 \
--table SYS_EXT_AREA \
--export-dir /user/root/SYS_EXT_AREA \
--columns ID,NAME,PID,SORT,LEVEL_EXT,LONGCODE,CODE,SIMPLE_NAME  \
--input-fields-terminated-by "\t" \
--input-lines-terminated-by "\n" \
--input-null-string "\\\\N" \
--input-null-non-string "\\\\N"